networks:
  activepieces:
    driver: bridge

services:
  app:
    depends_on:
      - postgres
      - redis
    image: mthenhaus/ap:0.0.1
    networks:
      - activepieces
    ports:
      - "3000:3000"
      - "4200:4200"
    volumes:
      - ./cache:/app/cache

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A79Vm5D4p2VQHOp2gd5
    networks:
      - activepieces
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.7
    networks:
      - activepieces
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: